# Ref: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
# and https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-semantic-release"
version = "7.32.2"
description = "Automatic Semantic Versioning for Python projects"
requires-python = ">=3.7"
license = { text = "MIT" }
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
]
readme = "README.rst"
authors = [{ name = "Rolf Erik Lekang", email = "me@rolflekang.com" }]
dependencies = [
  "click>=7,<9",
  "gitpython>=3.0.8,<4",
  "twine>=4,<5",
  "requests>=2.25,<3",
  "wheel",
  "jinja2>=3.1.2,<4",
  "python-gitlab>=2,<4",
  "tomlkit~=0.10",
  "dotty-dict>=1.3.0,<2",
  "dataclasses==0.8; python_version < '3.7.0'",
  "importlib-resources==5.7",
  "pydantic>=1.10.2,<2",
]

[project.scripts]
semantic-release = "semantic_release.cli:main"

[project.urls]
"Project Url" = "http://github.com/relekang/python-semantic-release"
Homepage = "https://python-semantic-release.readthedocs.io"

[project.optional-dependencies]
test = [
  "coverage>=6,<7",
  "pytest>=7,<8",
  "pytest-xdist>=2,<3",
  "pytest-mock>=3,<4",
  "pytest-lazy-fixture~=0.6.3",
  "pytest-cov>=4,<5",
  "responses==0.21.0",
  "requests-mock>=1.10.0,<2",
]
docs = ["Sphinx==5.2.3"]
dev = ["tox", "isort", "black"]
mypy = ["mypy", "types-requests"]

[tool.pytest.ini_options]
addopts = [
  "-ra",
  "--cache-clear",
  "--cov=semantic_release",
  "--cov-report",
  "html:coverage-html",
  "--cov-report",
  "term",
]
python_files = ["tests/test_*.py", "tests/**/test_*.py"]

# [tool.semantic_release]
# version_variable = ["semantic_release/__init__.py:__version__"]

[tool.coverage.run]
omit = ["*/tests/*"]

[tool.isort]
profile = "black"
skip = [".tox", "venv"]
combine_as_imports = true
group_by_package = true
default_section = "THIRDPARTY"
known_first_party = ["semantic_release"]
known_tests = ["tests"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "TESTS",
  "LOCALFOLDER",
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    mypy,
    py{37,38,39,310},
    coverage
skipsdist = True

[testenv]
passenv = CI
setenv =
    PYTHONPATH = {toxinidir}
    TESTING = True
deps = .[test]
commands =
    coverage run -p --source=semantic_release -m pytest -v {posargs:tests}

[testenv:mypy]
deps = .[mypy]
commands =
    mypy --ignore-missing-imports semantic_release

[testenv:coverage]
deps = coverage
commands =
    coverage combine
    coverage report -m
    coverage xml
"""
